### PR TITLE
FILE-344: add file's length, all tests passed

### PR DESCRIPTION
**Pull request by YuanZHANG910**
Need to see the size of a file.

### CODE REVIEW

**Comment by konradwudkowski** [comment]
It is now a bit confusing how file size constraint is applied, in one place we still set it to be 11mb but backend will reject based on a different value. Next person reading this in 6 months will have difficult time undrestanding

**Comment by YuanZHANG910** [comment]
the 11MB is a little beeconfusing, I did touth it becaurse i feel it may has the other usages. I think i should change it to 10MB as the max size.

**Comment by YuanZHANG910** [comment]
I have changed the max_file_size down to 10MB, 10MB is the constraints for maxSizePerItem from FILE-343(Implement File Size constraints https://jira.tools.tax.service.gov.uk/browse/FILE-343).

**Comment by konradwudkowski** [comment]
Unfortunately it's wrong now because the 10mb limit will apply to a request which contains more then just a file, so 10mb file will not fit

**Comment by YuanZHANG910** [comment]
so is that mean we should remove the max_file_size in the front-end

**Comment by JTY009** [comment]
Renamed branch to FILE-343_Implement_File_Size_Constraints

**Pull request closed without merging**
